name: My composite action
description: My example composite action

inputs:
  name:
    description: User name to greet
    required: false
    default: "Anonymous"

outputs:
  message:
    description: Greeting message
    value: ${{ steps.greeting.outputs.message }}
  version:
    description: Version
    value: ${{ steps.script.outputs.version }}

runs:
  using: composite
  steps:
    - name: Display greeting
      id: greeting
      shell: bash
      run: |
        message="Hello, ${{ inputs.name }}"
        echo "message=$message" >> $GITHUB_OUTPUT
    - run: echo "WOW"
      shell: bash
      if: ${{ inputs.name == 'Marshall' }}
    - name: Run script
      shell: bash
      id: script
      run: ${{ github.action_path }}/script.sh