name: Send discord notification

on:
  workflow_call:
    inputs:
      title:
        description: 'Title of embed'
        required: false
        type: string
        default: ''
      repository:
        description: 'Repository'
        required: true
        type: string

jobs:
  run:
    name: Send notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
      - name: Echo
        shell: bash
        run: echo "$PWD"
      - name: Cat
        shell: bash
        run: cat README.md
      - name: Make curl request
        shell: bash
        run: |
          json_payload=$(cat << EOF
          {
              "embeds": [
                      {
                          "type": "rich",
                          "title": "Hello there",
                          "description": "Testing workflow",
                          "color": "5763719",
                          "fields": [
                              {
                              "name": "Ref",
                              "value": "${{ github.ref }}"
                              },
                              {
                              "name": "URL",
                              "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                              },
                              {
                              "name": "Event",
                              "value": "${{ github.event_name }}"
                              }
                          ],
                          "footer": {
                              "text": "${{ github.actor }}"
                          }
                      }
              ]
          }
          EOF
          )

          curl -H "Content-Type:application/json" -d "$json_payload" "${{ secrets.DISCORD_WEBHOOK_URL }}"
